### ISSUE TITLE
Mac version 1.2.0: copy & paste support... please

### ISSUE THREAD

**Issue by franks42** [HTTPSChecker/releases#1]
Like your little app, but no copy&paste support... that's very "minimal".

**Comment by stilliard** [comment]
Hi @franks42 , looks like on Mac we need to add a title bar for this to work, we'll get right on it.
Thanks for reporting this.

**Comment by james-mckinnon** [comment]
Hi @franks42, 

Version 1.2.1 has just been released which adds the ability to copy and paste on Mac. If you are still having issues after updating, then please let us know.

Thanks

**Comment by franks42** [comment]
Excellent - with the copy&pasting of url's, the UI is a lot more pleasant - thanks for the speedy turn-around!
