### ISSUE TITLE
CSV of URLs not working

### ISSUE THREAD

**Issue by nkitiyakara** [HTTPSChecker/releases#10]
I can't seem to get a list of URLs from a CSV to work.  Every time I try, I just get a message saying "Error! There was an issue with the file you are trying to use," but there's no indication of what the error might be.  I'm sure that I have only one URL per line and that all the URLs are for the same host.  (In fact, I tried with just one url in the file.)  Since our site contains a lot of JS links, many standard crawlers (including HTTPSchecker) don't follow them properly and I really need to use a list of URLs that have been generated separately.  Thanks.

**Comment by stilliard** [comment]
Hi @nkitiyakara, Sorry about this issue, we do need to improve these error messages to be more specific soon. 
Here's an example file that I've just tested and seems to work for me, would you be able to try this file and see if it scans all 3 URLs inside? 
[sites-list-example.txt](https://github.com/HTTPSChecker/releases/files/834778/sites-list-example.txt)

If this works but your other file still does not would you be able to share your file or a cut down version of it?
Thanks.

**Comment by nkitiyakara** [comment]
Unfortunately, your sample file also doesn't work for me.

![image](https://cloud.githubusercontent.com/assets/968773/23807875/75ee1602-0595-11e7-97c0-3e28f211f686.png)

**Comment by stilliard** [comment]
Ah I've just tried on Windows and there does seem to be an issue running the sample file too. 
Apologies about this, I'll get to work on a fix for CSV uploads on Windows now & we should be able to release a new version with this fix early next week. Hope this is ok.

**Comment by nkitiyakara** [comment]
That should be fine.  Thanks for the quick response.

**Comment by stilliard** [comment]
No problem, thank you for reporting this.

**Comment by stilliard** [comment]
Hi @nkitiyakara, 
Just to keep you updated the latest version is all coded up with this fix and a few other tweaks. 
We should finish testing shortly and I believe we'll have it released early tomorrow.

**Comment by stilliard** [comment]
Hi @nkitiyakara ,
We've now released the new version of HTTPS Checker with a fix for this issue. 
Hope this works for you, let me know if you find any other issues, thanks.

**Comment by stilliard** [comment]
Just closing this issue for now, but if you have any problems please open a new issue and i'll be happy to help, thank you.
