### ISSUE TITLE
Active mixed content

### ISSUE THREAD

**Issue by cjc1867** [HTTPSChecker/releases#12]
This is telling me I have active mixed content with a particular plugin called WP Portfolio since I am not using it I disabled it, ran the test again and same message.

I then deleted the plugin and re run the test and it still tells me I have the same problems with the deleted plugin.

Why? Surely a bug in the system.

**Comment by stilliard** [comment]
Hey @cjc1867,
Sorry to hear about this, I'd be happy to look into this for you now, would you be able to send me a link to the site you're scanning to test?
You can submit it to me over andrew@httpschecker.net to avoid pasting it here if you'd like?

**Comment by cjc1867** [comment]
Hi
The website is https://towywebdesigns.uk

Struggling to get hsts working with plugins or is your program not picking it up?

Thanks

Colin

**Comment by stilliard** [comment]
Thanks Colin,
I've tested the site but I'm not seeing any mixed content reports.
Would you mind restarting the app to see if it no longer shows the warning for you? If it disappears I'll investigate if we're caching the responses and get a fix ready for that, thanks. 

With HSTS which wordpress plugin are you using to enable this? 
Currently I'm see'ing the following headers from your site so no HSTS yet but hopefully it works soon.

~ → curl -I https://towywebdesigns.uk/
HTTP/1.1 200 OK
Date: Fri, 02 Jun 2017 21:02:19 GMT
Server: Apache
X-Powered-By: PHP/7.0.18
Vary: Accept-Encoding,Cookie
Cache-Control: max-age=3, must-revalidate
WP-Super-Cache: Served supercache file from PHP
Content-Type: text/html; charset=UTF-8
X-Backend-Server: standard_limited_backend/web4.hosting.stackcp.net

**Comment by cjc1867** [comment]
Hi
I tried earlier restarting and it still came up with the same problems but now the problems have gone. Earlier it was reporting just 1 page and then every page so yes got to be a caching problem.

I have tried most of the plugins and they don't work or give me white screen of death. It's driving me up the wall. I even got some code off one website to put in the functions file and again it didn't work.

Cheers

Colin

**Comment by stilliard** [comment]
Thanks I'll get the caching issue looked into first thing monday. 

Ah sorry to hear about them causing the white screen of death. 
Do you have access to your .htaccess file?
If so, you can probably do it by adding the following:

```
Header set Strict-Transport-Security "max-age=31536000" env=HTTPS
```

Hope it helps.

**Comment by cjc1867** [comment]
Hi
Tried another plugin but I think I have already tried it. So how long does it take for hsts to be recognised?

cheers

Colin

**Comment by stilliard** [comment]
Should be pretty much instant.
Just checked your site with this online tool to check the response headers
and I can see your HSTS is working.
http://web-sniffer.net/

Glad you've got it all setup!

Best wishes,
from Andrew Stilliard.

**Comment by cjc1867** [comment]
Hi again
It doesn't work in your program but I tried to submit it to https://hstspreload.org/ and the check said the max age is not old enough ie 18 weeks but this was recommended by the author of the plugin.

I have increased the max age to 10886400 and now the above website doesn't recognise hsts again, maybe there is a time delay or something else.

Cheers

Colin

**Comment by cjc1867** [comment]
Hi
I placed some code in .htaccess instead of using the WordPress plugin and it worked straightaway. I rerun your program and I got no errors.

Colin

**Comment by stilliard** [comment]
Hi Colin,
That's brilliant, glad you've got it working!
Let me know if you find any issues.
