### ISSUE TITLE
Issues found even when HTML is commented out

### ISSUE THREAD

**Issue by CostaC** [HTTPSChecker/releases#13]
HTTPSChecker finds:

`Passive Mixed Content	Insecure Icon: <link rel="shortcut icon" href="http://www.DOMAIN.com/favicon.ico" type="image/x-icon" />`

even though that html is within `<!--  -->` tags

**Comment by stilliard** [comment]
Hi @CostaC, thanks for reporting this. 
We originally looked to fix this bug but we found it actually helps people track down a few edge cases, such as IE conditional comments, but also any code left in a comment could be un-commented in the future and so it's worth quickly updating that code too or considering removing the comment.
Hope this helps.
