### ISSUE TITLE
Relative URI on https Page are marked as error

### ISSUE THREAD

**Issue by deep-blue** [HTTPSChecker/releases#15]
The https page is not publicly available at the moment, but it contains something like
`<link rel="icon" href="/site/meinestadt/resourceCached/3.43.13/htdocs/img/favicons/meinestadt_de_favicon_32.png" />`

which gives an error report:

Passive Insecure Content | Insecure Icon: `<link rel="icon" href="http://static.meinestadt.de/site/meinestadt/resourceCached/3.43.13/htdocs/img/favicons/meinestadt_de_favicon_32.png" />`
-- | --

**Comment by stilliard** [comment]
Hi @deep-blue , thanks for using our tool. 

If it's showing that full URL found it must be on the page somewhere, but I have seen some times when web servers will modify the code and put full paths in, the best way to check this is to view source for the page directly in your browser. 

Let me know if there's still a problem though or if there's anything else I can help with thanks.

**Comment by deep-blue** [comment]
The page will be publicly available during the next week. For now I add the downloaded version:
`curl -o https_auto.html "https://auto.preprod.meinestadt.de"`
[https_auto.html.txt](https://github.com/HTTPSChecker/releases/files/1166041/https_auto.html.txt)
As you can see - it is exactly like i cited above.
BTW: it's all in line 4 
.txt because .html is not allowed here

**Comment by stilliard** [comment]
Ah I see. 
I've downloaded the html file and created a local server for it. 
I've run https checker against it just but it doesn't appear to be telling me it's found the same mixed content as it did for you. 
Is it possible that at the time of your original crawl it was set with this full url and has now been changed?

**Comment by deep-blue** [comment]
Currently I cannot reproduce it against our pre production environment. There was no deployment or any other change - I'll check it again when it is deployed to prod.

Thank you anyway for your quick response and investigation.

**Comment by stilliard** [comment]
Ok sure, glad it's ok now at least. 
I'll keep an eye out for any other tickets around rouge issues showing up just in case, thanks for reporting it anyway. 
Let me know if there's anything else I can help with or if you have any ideas for improving the tool, always eager to hear how we can improve it.
