### ISSUE TITLE
Scan isn't identifying javascript src mixed content

### ISSUE THREAD

**Issue by quadland** [HTTPSChecker/releases#16]
I'm aware of some mixed content on the site, but the scan isn't identifying http javascript source references from the HTTPS page request.  Can you clarify if it that is or is not a feature that I should expect the scan to identify?

**Comment by stilliard** [comment]
Hi @quadland ,

The app may not be able to find content that only appears based on javascript within a page as we do not currently execute the page as a full browser would. 

However, if you have a paid subscription you can use our HTTPS Reporter service on your site and it will pick up all issues as soon as any visitors browser see's it.

**Comment by stilliard** [comment]
Hey @quadland ,
Just checking up to see how you got on, hope everything is working well for you. 
I'll close this ticket for now, but please let me know if there's anything I can help with, thank you.
