### ISSUE TITLE
Report Link omits root domain in url

### ISSUE THREAD

**Issue by ghost** [HTTPSChecker/releases#17]
After the latest update in the report results, the link to the page it use to be clickable to take you to the page.  It now omits the root domain and is unusable.

**Comment by stilliard** [comment]
Hi @mtkennedy,
Sorry about this issue, we'll get a fix up first thing next week when we're back. 
Thank you for reporting this!

**Comment by stilliard** [comment]
Hey @mtkennedy ,
Our latest patch is now available, if you open the app it should start to update automatically. 
Thanks again for reporting this!
