### ISSUE TITLE
Contact Form broken on homepage

### ISSUE THREAD

**Issue by ericlaw1979** [HTTPSChecker/releases#2]
Looks like it is submitting to your dev server rather than production:
![image](https://cloud.githubusercontent.com/assets/4192774/18716367/29123d10-7fe2-11e6-88a2-a095174b7607.png)

**Comment by stilliard** [comment]
Hi @ericlaw1979 ,
Thanks for reporting this, we will fix this right away.

**Comment by stilliard** [comment]
Forgot to close this yesterday, thanks again for reporting this.
