### ISSUE TITLE
alternative ports unsupported?

### ISSUE THREAD

**Issue by reh-NAH-toos** [HTTPSChecker/releases#20]
Hey!
I couldn't really find more information on the homepage about using alternative ports to 80/443.
Being able to use a different port would be awesome as i bought the licence for the HTTPS Checker Tool to be able to check even local deployed websites.
I updated to the most current version (2.0.3) on Linux and when im trying to crawl with port 8081 it only accesses one page and finishes the crawling.

Help needed!

**Comment by stilliard** [comment]
Hey @rene-pxl,
Thanks for contacting us about this.
We're looking into this now as I can reproduce this as well.

For now a temporary work around for you to crawl local sites could be to switch the site running on port 80 or you could use a service suck as localtunnel (https://localtunnel.github.io/www/) or ngrok (https://ngrok.com/) to make a temporary public URL for your site.

I'll keep you updated with this though and hope to get back to your soon. 
Hope this is ok.

**Comment by stilliard** [comment]
Hi @rene-pxl ,
Sorry for the delay in getting back to you. 
We've found and resolved the issue in the app to bring in support for crawling any port you specify. 

As it's so close to Christmas we'll be holding off the release until the new year but we hope to release at the very start of January.

**Comment by reh-NAH-toos** [comment]
Hey Andrew!

thanks for the headup on this case.
Thanks for taking a look into this issue and fixing it.
Looking forward to the new version.

Best regards and happy holidays,

René

Quoting Andrew Stilliard <notifications@github.com>:

**Comment by stilliard** [comment]
Hey René,
Happy New Year!

We've just released a new version of HTTPS Checker which fixes support for scanning sites on alternative ports!

Let me know how this goes & if there's anything I can do to help.
