### ISSUE TITLE
Can't Export CSV

### ISSUE THREAD

**Issue by btreloar** [HTTPSChecker/releases#23]
Ran report on my own website and tried (several times) to download a CSV file. Each time it failed with an error message at the bottom right of my screen. I can't see the entire message, but it says I should report it. The error begins with ENOENT No such file or directory, open: then a path to a folder in httpscheduler under my user directory. This scan took quite awhile to run .. is there any way to save it? Or must I just rerun it when you have helped me fix whatever's wrong?

FWIW, I'm running Windows 10 Home, up to date.

[report.pdf](https://github.com/HTTPSChecker/releases/files/1713663/report.pdf)

**Comment by stilliard** [comment]
Hi @btreloar ,
Thank you for reporting this to us. 

Would you be able to check inside the following folder on your computer to see if the CSV saved here?
C:\Users\YourUserName\AppData\Local\Httpschecker\Logs

Also when you clicked to save as CSV, did it show a popup asking where to save the file to?

**Comment by stilliard** [comment]
Hi @btreloar ,
Sorry this has been so delayed.

We've just released a new version of HTTPS Checker which should fix edge cases where we couldn't export the CSV correctly.

If you get a chance, could you please let me know if this works for you, thank you.

**Comment by stilliard** [comment]
Closing this support ticket for now but please let me know if the issue persists or if there's anything else I can help with. Thank you.
