### ISSUE TITLE
Inconsistent Pro Version Login

### ISSUE THREAD

**Issue by PaulyBee** [HTTPSChecker/releases#26]
Hi

I have a Pro version that has worked well.  However since the recent upgrade I am not able to login permanently and often its the luck of the draw if I can log in with the Pro version at all.  :(  I get the message 'unexpected token < in JSON at position 0

**Comment by stilliard** [comment]
Hi Paul,
Thanks for reporting this, I'll reply to you directly as I see you've emailed us too.
Thank you.
