### ISSUE TITLE
Only crawls 1 page, doesn't crawl entire site?

### ISSUE THREAD

**Issue by afalk42** [HTTPSChecker/releases#4]
Good morning, I bought a personal license this week to allow me to test my blog and website after the recent http -> https migration. When I run HTTPS Checker on https://blog.altova.com it crawls a thousand pages or so and gives me a clean report (after fixing all the mixed-content issues it found earlier). 
However, when I run it on https://www.altova.com it only crawls one page and then stops. Help? Why is it not crawling the entire site?
It reports that I'm not using the HSTS header yet, which is indeed by design. I want to make sure first that everything is working 100% before turning on that header.

**Comment by stilliard** [comment]
Hi @afalk42 ,
Thanks for using our app and for buying a licence with us. 

I've had a look at your site and it appears your robots.txt file is currently set to block all bots. 
Normally we follow the rules of this file for crawling sites, but in the app's advanced options you can un-tick "Use Robots.txt File Rules" which should then allow it to crawl the entire site.

Hope this helps.

**Comment by afalk42** [comment]
Got it, thank you. That is apparently a temp version of the file during the migration. We will replace that with the real one ASAP. Thank you also for mentioning the setting - found it and it works great now! Thank you!!

**Comment by stilliard** [comment]
Glad I could help @afalk42 , let me know if there's anything else we can help with.
