### ISSUE TITLE
Constant Updates

### ISSUE THREAD

**Issue by tijamo** [HTTPSChecker/releases#6]
My app just updated and now keeps downloading and installing updates repeatedly.

**Comment by james-mckinnon** [comment]
Hi @tijamo ,

Sorry to hear that you're having issues with the updated app. If possible, could we have a bit more information please? At the moment, we just need to know the Operating System and Operating System Version that you are running.

Thanks

**Comment by tijamo** [comment]
Hi,

I’m running the latest stable release of macOS Sierra (version 10.12).

This is what I’m seeing:

Thanks,

Tim

**Comment by stilliard** [comment]
Hi @tijamo, 

Sorry about this, we released the new version but forgot to bump the old version in the app. 

If you open the app again now it should download the latest version again, but this time it should then no longer try to update repeatedly. 

Thank you for reporting this.

**Comment by tijamo** [comment]
Hi Andrew,

That’s sorted it – thank you!

Tim
