### ISSUE TITLE
Not scanning on pre-production site.

### ISSUE THREAD

**Issue by Sliknikim** [HTTPSChecker/releases#8]
I can run the tool on our live sites but when using any pre-production url it only does one page and then stops.  One of our pre-production site I'm testing on is photo-master.pre.planetart.com.  Can you advise?

**Comment by stilliard** [comment]
Hi @Sliknikim,
Under the advanced section, have you tried disabling robots.txt parsing as
it appears that site is set to block bots atm. I hope this helps.

Best wishes,
from Andrew Stilliard.

**Comment by Sliknikim** [comment]
Yes, that was it.  It’s on by default but after I unchecked it it’s now running the full scan.

Thanks!

**Comment by Sliknikim** [comment]
yes that was it!  Thanks!
